README.md
milatools/cli/commands.py
milatools/cli/init_command.py
tests/cli/test_init_command/test_fixes_overly_general_entry.txt
tests/cli/test_init_command/test_setup_ssh_empty_confirm_changes_.txt
tests/cli/test_init_command/test_setup_ssh_has_comment_and_entry_confirm_changes_.txt
tests/cli/test_init_command/test_setup_ssh_has_comment_confirm_changes_.txt
tests/cli/test_init_command/test_setup_ssh_has_different_indent_confirm_changes_.txt
tests/cli/test_init_command/test_with_existing_entries__.txt
tests/cli/test_init_command/test_with_existing_entries_mila_.txt
tests/cli/test_init_command/test_with_existing_entries_mila_computenode_.txt
tests/cli/test_init_command/test_with_existing_entries_mila_cpu_.txt
tests/cli/test_init_command/test_with_existing_entries_mila_cpu_mila_computenode_.txt
tests/cli/test_init_command/test_with_existing_entries_mila_gpu_.txt
tests/cli/test_init_command/test_with_existing_entries_mila_gpu_mila_computenode_.txt
tests/cli/test_init_command/test_with_existing_entries_mila_mila_computenode_.txt
tests/cli/test_init_command/test_with_existing_entries_mila_mila_cpu_.txt
tests/cli/test_init_command/test_with_existing_entries_mila_mila_cpu_mila_computenode_.txt
tests/cli/test_init_command/test_with_existing_entries_mila_mila_gpu_.txt
tests/cli/test_init_command/test_with_existing_entries_mila_mila_gpu_mila_computenode_.txt

* Add a `mila-cpu` entry that enables `ssh mila-cpu` directly to a compute node.
* Deactivate `mila-gpu` until the next Slurm update.
* Make sure that `mila code` and `mila serve` set an informative job name, for metric collection.

Add mila-cpu entry and add job names to allocations

---

milatools/cli/commands.py

Following a suggestion from @lebrice, this adds a welcome message at the end of `mila init` that invites user to ssh into the cluster and links the documentation and Slack channel.

Add a welcome message after mila init

---

milatools/cli/commands.py
milatools/cli/remote.py
milatools/cli/utils.py

Added a custom Exception class SSHConnectionError. Wraps Remote class with try except raise condition. Prints more explicit error message with possible workarounds instead of basic Exception error message which recommends to file a bug.

MT-55 Catch and handle Paramiko SSH errors

---

milatools/cli/commands.py

- Fixes an indentation bug introduced by #52 which removed the `disk-quota` step of the `mila code` command.

Bugfix: Actually run disk-quota in `mila code`

---

milatools/cli/commands.py
milatools/cli/init_command.py
milatools/cli/utils.py
milatools/cli/vscode_utils.py
tests/cli/test_init_command.py
tests/cli/test_init_command/test_setup_vscode_settings_accept_None_.md
tests/cli/test_init_command/test_setup_vscode_settings_accept_initial_settings1_.md
tests/cli/test_init_command/test_setup_vscode_settings_accept_initial_settings2_.md
tests/cli/test_init_command/test_setup_vscode_settings_accept_initial_settings3_.md
tests/cli/test_vscode_utils.py

- `mila init` now tries to update the User settings of VsCode with a  `"remote.SSH.connectTimeout": 60`
Are there other useful entries we should add?
Anything particular to Windows/Mac/Linux?
Let us know! :)
TODOs:

Setup VsCode settings for remote development during `mila init`

---

milatools/cli/init_command.py

- Fixes #82
Weird that this bug got through the CI, honestly!
Once we add code-coverage we might get a better idea how this happened. Essentially, there was an extra "," in a string inside parentheses, which made this into a tuple instead of a string.

Fix a bug in `mila init` (see desc.)

---

milatools/cli/commands.py
milatools/cli/local.py
milatools/cli/profile.py
milatools/cli/remote.py
milatools/cli/utils.py
tests/cli/test_commands.py
tests/cli/test_init_command.py
tests/cli/test_remote.py

Add type annotations to the package, without changing anything about how the code works, or how it is tested.
This contains mostly the typing-related changes from #61

(only) add type hints

---

.github/workflows/publish.yml
pyproject.toml

- Adds a new "Publish package" GitHub Action that gets triggered when a new release is created on GitHub.
- Also uses the poetry_dynamic_versioning plugin to set the version based on the tag, similar to what versioneer would do with a setup.py.

Add publish GitHub Action workflow

---

.github/workflows/publish.yml
pyproject.toml

During the recent release, the package version was 0.0.0 in the GitHub CI: 
https://github.com/mila-iqia/milatools/actions/runs/7572023233/job/20621010227#step:6:36
This is the same issue as in https://github.com/mtkennerly/poetry-dynamic-versioning/issues/145
I made the release myself with `poetry publish --build` on my local machine, although in retrospect I probably shouldn't have done that.
This PR is an attempt to fix the issue with the dynamic versioning in the GitHub CI so that the publishing it actually taken care of by GitHub Actions for the next release. I'm trying to do this by adapting the solution proposed in https://github.com/mtkennerly/poetry-dynamic-versioning/issues/145#issuecomment-1719645691 by installing the dynamic versioning plugin explicitly in the CI. 
I find it …

Fix dynamic versioning not working in the CI

---

.github/workflows/build.yml
.pre-commit-config.yaml
milatools/cli/commands.py
milatools/cli/local.py
milatools/cli/profile.py
milatools/cli/remote.py
milatools/cli/utils.py
milatools/cli/vscode_utils.py
poetry.lock
pyproject.toml
tests/cli/common.py
tests/cli/conftest.py
tests/cli/test_remote.py
tests/cli/test_slurm_remote.py
tests/cli/test_utils.py
tests/cli/test_vscode_utils.py

- Drops support for Python 3.7:
- Updates the pre-commit hooks to include the --select=UP flag (pyupgrade equivalent with ruff)
- Updates the build workflow
- Removes unnecessary checks / imports from python 3.7

Drop support for python 3.7

---

milatools/cli/init_command.py
tests/cli/test_init_command/test_fixes_overly_general_entry.txt
tests/cli/test_init_command/test_setup_ssh_empty_confirm_changes_drac_.md
tests/cli/test_init_command/test_setup_ssh_empty_confirm_changes_no_drac_.md
tests/cli/test_init_command/test_setup_ssh_has_comment_and_entry_confirm_changes_drac_.md
tests/cli/test_init_command/test_setup_ssh_has_comment_and_entry_confirm_changes_no_drac_.md
tests/cli/test_init_command/test_setup_ssh_has_comment_and_entry_with_extra_space_confirm_changes_drac_.md
tests/cli/test_init_command/test_setup_ssh_has_comment_and_entry_with_extra_space_confirm_changes_no_drac_.md
tests/cli/test_init_command/test_setup_ssh_has_comment_confirm_changes_drac_.md
tests/cli/test_init_command/test_setup_ssh_has_comment_confirm_changes_no_drac_.md
tests/cli/test_init_command/test_setup_ssh_has_different_indent_confirm_changes_drac_.md
tests/cli/test_init_command/test_setup_ssh_has_different_indent_confirm_changes_no_drac_.md
tests/cli/test_init_command/test_setup_windows_ssh_config_from_wsl_accept_.md
tests/cli/test_init_command/test_setup_windows_ssh_config_from_wsl_reject_.md
tests/cli/test_init_command/test_with_existing_entries_has_mila_compute_entry_has_mila_cpu_entry_has_mila_entry_has_drac_entries_.md
tests/cli/test_init_command/test_with_existing_entries_has_mila_compute_entry_has_mila_cpu_entry_has_mila_entry_no_drac_entries_.md
tests/cli/test_init_command/test_with_existing_entries_has_mila_compute_entry_has_mila_cpu_entry_no_mila_entry_has_drac_entries_.md
tests/cli/test_init_command/test_with_existing_entries_has_mila_compute_entry_has_mila_cpu_entry_no_mila_entry_no_drac_entries_.md
tests/cli/test_init_command/test_with_existing_entries_has_mila_compute_entry_no_mila_cpu_entry_has_mila_entry_has_drac_entries_.md
tests/cli/test_init_command/test_with_existing_entries_has_mila_compute_entry_no_mila_cpu_entry_has_mila_entry_no_drac_entries_.md
tests/cli/test_init_command/test_with_existing_entries_has_mila_compute_entry_no_mila_cpu_entry_no_mila_entry_has_drac_entries_.md
tests/cli/test_init_command/test_with_existing_entries_has_mila_compute_entry_no_mila_cpu_entry_no_mila_entry_no_drac_entries_.md
tests/cli/test_init_command/test_with_existing_entries_no_mila_compute_entry_has_mila_cpu_entry_has_mila_entry_has_drac_entries_.md
tests/cli/test_init_command/test_with_existing_entries_no_mila_compute_entry_has_mila_cpu_entry_has_mila_entry_no_drac_entries_.md
tests/cli/test_init_command/test_with_existing_entries_no_mila_compute_entry_has_mila_cpu_entry_no_mila_entry_has_drac_entries_.md
tests/cli/test_init_command/test_with_existing_entries_no_mila_compute_entry_has_mila_cpu_entry_no_mila_entry_no_drac_entries_.md
tests/cli/test_init_command/test_with_existing_entries_no_mila_compute_entry_no_mila_cpu_entry_has_mila_entry_has_drac_entries_.md
tests/cli/test_init_command/test_with_existing_entries_no_mila_compute_entry_no_mila_cpu_entry_has_mila_entry_no_drac_entries_.md
tests/cli/test_init_command/test_with_existing_entries_no_mila_compute_entry_no_mila_cpu_entry_no_mila_entry_has_drac_entries_.md
tests/cli/test_init_command/test_with_existing_entries_no_mila_compute_entry_no_mila_cpu_entry_no_mila_entry_no_drac_entries_.md

This makes it much more convenient to connect to clusters where 2FA is enabled, as the procedure needs to be done only one per machine boot (instead of once every 10 minutes).

Change ControlPersist from 600 to 'yes'

---

milatools/cli/commands.py
milatools/cli/init_command.py
milatools/cli/remote.py
milatools/cli/utils.py
milatools/utils/vscode_utils.py
tests/cli/test_init_command.py
tests/cli/test_remote.py
tests/cli/test_remote/test_srun_transform_persist_localhost_.md
tests/cli/test_utils.py
tests/integration/test_code_command.py
tests/integration/test_slurm_remote.py

- Fix missing `cd $SCRATCH` before `salloc`/`sbatch` on DRAC clusters
- Fix bug which would try to connect to full hostname of the DRAC compute nodes instead of just the node name (which have dedicated entries in the SSH config)
- ~~Fix issue with syncing of vscode extensions happening in the foreground instead of the background~~ Left in the foreground for now (otherwise it clutters and overwrites other output messages). 
- Attempt to fix issue of VsCode window requiring a password to connect to compute nodes:
- Adjust `mila init`:
- setup the SSH connection to compute nodes on DRAC clusters (not just mila)
- Run `ssh-copy-id` with the identity file defined in the ssh config instead of the default `~/.ssh/id_rsa`.

Fix bug with `mila code --cluster=<DRAC>`

---

.github/workflows/build.yml
.github/workflows/full_cluster_tests.yml
.github/workflows/testing.yml

- Extracts the integration test part of `build.yml` into a reusable workflow called `testing.yml`.
- This workflow now also explicitly requires an existing SSH connection to be alive (a socket at the ControlPath of the SSH config) in order to run tests on the DRAC clusters
- Also adds a new `full_cluster_tests.yml` workflow that is run periodically (once a week) and runs the integration tests on all slurm clusters (not just `'mila'`, as in `build.yml`).

Run integration tests with all clusters periodically

---

.github/workflows/build.yml

Fix some weird issue that seem to be related to using setup-python with `cache: poetry` on MacOS, for example here: https://github.com/mila-iqia/milatools/actions/runs/8834122225/job/24257059736?pr=112#step:4:53

Fix issues with macOS in CI

---

.github/workflows/build.yml
milatools/cli/__init__.py
milatools/cli/commands.py
milatools/cli/utils.py
milatools/utils/compute_node.py
milatools/utils/local_v1.py
milatools/utils/local_v2.py
milatools/utils/remote_v1.py
milatools/utils/remote_v2.py
milatools/utils/runner.py
poetry.lock
pyproject.toml
tests/cli/common.py
tests/cli/test_init_command.py
tests/cli/test_utils.py
tests/conftest.py
tests/integration/conftest.py
tests/integration/test_code_command.py
tests/integration/test_slurm_remote.py
tests/integration/test_sync_command.py
tests/utils/runner_tests.py
tests/utils/test_compute_node.py
tests/utils/test_local_v1.py
tests/utils/test_local_v2.py
tests/utils/test_remote_v2.py
tests/utils/test_vscode_utils.py

This PR adds some new functions and classes which will be used in the near future to significantly refactor most commands of milatools.
Once these commands are made to use the content of this PR, they will:
- Properly support ssh keys with a passphrase
- Properly support clusters where 2FA is enabled (only goes through 2FA once)
- Resolve all paramiko issues
- Greatly reduce the connection latency for all commands that connect to the `mila` cluster (such as `mila code`).
I would appreciate it if you could take a quick look at a few particular things, if you feel like it of course:
- LocalV2
- the `run` function: https://github.com/lebrice/milatools/blob/add_computenode_localv2/milatools/utils/local_v2.py#L102
- the `run_async` function: …

Add `ComputeNode`, `LocalV2` + deprecate `RemoteV1` and `LocalV1`

---

.github/workflows/build.yml
.github/workflows/full_cluster_tests.yml
.github/workflows/testing.yml

- Make it so the build workflow doesn't run on changes to the README (as is the case in #122 )
- The build workflow will now have a concurrency setting to cancel previous workflow runs on a push to the same branch.
- Pass the codecov token explicitly to fix issues with codecov upload step
- Increase the length allowed for integration tests

Tweak build workflow

---

milatools/cli/commands.py
milatools/cli/utils.py
tests/cli/test_commands.py
tests/cli/test_commands/test_help_mila_code_.txt
tests/cli/test_commands/test_help_mila_serve_aim_.txt
tests/cli/test_commands/test_help_mila_serve_lab_.txt
tests/cli/test_commands/test_help_mila_serve_mlflow_.txt
tests/cli/test_commands/test_help_mila_serve_notebook_.txt
tests/cli/test_commands/test_help_mila_serve_tensorboard_.txt
tests/cli/test_commands/test_invalid_command_output_mila_code___boo_.txt

- Adds a --salloc flag which is exaclty the same as using the '--alloc' flag (without the --persist) flag.
- Adds a --sbatch flag which is the same as doing --persist --alloc ...
I think these are more naturally understood as the argument that are passed to `salloc` and `sbatch` respectively.
Also, these two new args are in a mutually exclusive group with --persist.

Tweak cli. add --sbatch and --salloc as alternatives to --alloc and --persist

---

README.md

Recommend using `pipx` instead of `pip` for isolated environments
(from the docs:)

Recommend using `pipx`

---

.github/workflows/build.yml
milatools/cli/code.py
tests/cli/test_code.py
tests/integration/test_code/test_code_mila__salloc_.txt
tests/integration/test_code/test_code_mila__sbatch_.txt
tests/integration/test_sync_command.py

When a user launches `mila code` from WSL, it should end up running `powershell.exe code (...)`, otherwise the vscode window opens a local file (that doesn't exist) instead of opening on the remote.
This fixes a bug whereby the `running_inside_WSL` function wasn't being called anymore in `mila code`.
Signed-off-by: Fabrice Normandin <normandf@mila.quebec>

Bugfix for mila code in WSL

---

milatools/cli/utils.py

Fix a bug in the `milatools.cli.utils.batched` function in Python versions >= 3.12. 
This function is called by `milatools.utils.vscode_utils._find_code_server_executable` which itself is called by `mila code` indirectly.
This probably means that the `mila code` command was erroring out in Python 3.12 and above, but I'm not sure.

Fix `milatools.cli.utils.batched` in python 3.12

---

milatools/cli/commands.py
milatools/cli/init_command.py
tests/cli/test_code.py
tests/cli/test_init_command.py
tests/conftest.py

When running in WSL, it looks like we are copying the `id_rsa` before creating them. In this PR, we check if we need to copy them after the creation. 
I am not sure what to do if the Windows ssh config file did not changed, should we still copy the `id_rsa` ? I am referring to this [line ](https://github.com/mila-iqia/milatools/blob/4ffdbaa92d6c1f7fb3c5249d0108d10b24653806/milatools/cli/init_command.py#L212)

Fix copying of SSH keys from WSL to Windows
